// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzexxyiZmlVuakEmkI_75acz0mvVubdo8',
    appId: '1:793343546367:web:a7b1ad37fa35a84e000dca',
    messagingSenderId: '793343546367',
    projectId: 'diet-app-2',
    authDomain: 'diet-app-2.firebaseapp.com',
    storageBucket: 'diet-app-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_4y3Xchm511imA7y7NNxOBcmO8ST7Wk',
    appId: '1:793343546367:android:9cc5d9db7bc6fb9c000dca',
    messagingSenderId: '793343546367',
    projectId: 'diet-app-2',
    storageBucket: 'diet-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0L41WK2BeqyChJ5leAEz-dqcMmxh5CYs',
    appId: '1:793343546367:ios:5f6e2abfc85b0b92000dca',
    messagingSenderId: '793343546367',
    projectId: 'diet-app-2',
    storageBucket: 'diet-app-2.appspot.com',
    iosClientId: '793343546367-94snaho7thhg6v3vu1cjng0i8ev6pikn.apps.googleusercontent.com',
    iosBundleId: 'com.wassabi.dietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0L41WK2BeqyChJ5leAEz-dqcMmxh5CYs',
    appId: '1:793343546367:ios:5f6e2abfc85b0b92000dca',
    messagingSenderId: '793343546367',
    projectId: 'diet-app-2',
    storageBucket: 'diet-app-2.appspot.com',
    iosClientId: '793343546367-94snaho7thhg6v3vu1cjng0i8ev6pikn.apps.googleusercontent.com',
    iosBundleId: 'com.wassabi.dietApp',
  );
}
